install.packages("pscl") # updated on a personal directory
install.packages("dplyr")
install.packages("magrittr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("coin")
install.packages("devtools")
install.packages("gamlss")
#install.packages("GenomeInfoDb")
BiocManager::install("MAST")
BiocManager::install("zinbwave")
BiocManager::install("DESeq2")
BiocManager::install("BiocParallel")
BiocManager::install("scran")
#BiocManager::install("lefser")
# install.packages("/Users/hunyongcho/Downloads/lefser_1.0.0.tar.gz", repos = NULL, INSTALL_opts = c('--no-lock'))